# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ccc172f0318c7c9a6c64a57ac008afbe1ac43b682e2a0359bff0c736598b53ac22abd26a50dbe93ce1d7f16a25b74b71833a91d92efd53b144658ece0d826e

test:
  secret_key_base: 93eb93fa1ca7e192212189803e05e26934d71035fcb6f3e25e3e3d025ef86ddd4fcfe3478ae5ada826c88c8ff812084db36ed5bf0884a67e42ccecc48a641adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
